- hosts: dnac_servers
  collections:
    - cisco.dnac
  tags: 
    - create
    - get
    - delete
  vars_files:
    - host_vars/credentials.yml
  gather_facts: no

  tasks:
  - name: Create Tag
    tags: create
    block:
    - name: Create tag with name "My_TAG"
      cisco.dnac.tag:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        state: present
        description: My Tag
        name: My_TAG
      register: create_result

  - name: Get Tag
    tags: get
    block:
    - name: Get tag with name "My_TAG"
      cisco.dnac.tag_info:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        name: My_TAG
      register: get_result

    - name: Show tags with name "My_TAG"
      debug:
        msg: "{{ get_result }}"
    
    - name: Delete Tag    
      tags: delete
      block:
    - name: Delete tag with name "My_TAG"
      cisco.dnac.tag:
        dnac_host: "{{dnac_host}}"
        dnac_username: "{{dnac_username}}"
        dnac_password: "{{dnac_password}}"
        dnac_verify: "{{dnac_verify}}"
        state: absent
        name: My_TAG
      register: delete_result

      
